### PR TITLE
Apply the extranonce subscription patch

### PR DESCRIPTION
**Pull request by jcwoltz**

### CODE REVIEW

**Comment by jcwoltz** [comment]
I have this patch running on multiple zeus devices. I do not have any gridseeds to test with.

**Comment by dmaxl** [comment]
I saw something similar on upstream several weeks ago, has this been
incorporated there yet?

**Comment by jcwoltz** [comment]
I dont know. I'm using it successfully on my zeus scrypt rigs.

**Comment by dmaxl** [comment]
Sorry for the delay. I just looked over the patch and comparing to the version from Nicehash (nicehash/cgminer-ckolivas@4e9c7ce68ed91ec9189d83c35b2237aca65f2b7f) yours is missing a second call to `check_extranonce_option()` in `cgminer.c:stratum_works()`. Was that intentional or just an omission? Otherwise I'm happy to merge the changes.

**Comment by jcwoltz** [comment]
It was not intentional on my part. It must not have been in the patch I looked at.

**Comment by dmaxl** [comment]
Nicehash version of patch merged in commit 0f70139ddc3fe382bbba45d00213382976de9b55.

**Pull request closed without merging**
